import { EXPLANATIONS, EXPLANATIONS_TH, SYSTEMS, type Concept, type SystemId } from '../app/anatomy';
import type { SeniamEntry } from './seniam';

/**
 * Specific per-concept descriptions.
 *
 * Accuracy policy (this atlas is used by teachers/researchers):
 * - Functional claims appear ONLY for entries verified against the source
 *   (SENIAM Function rows, or the vetted organ explanations).
 * - Everything else is composed from provable facts: side parsed from the
 *   name, region from a conservative keyword table, and the vetted system
 *   role sentence. Nothing is guessed.
 */

// [keyword, regionEn, regionTh] — first match wins; order is significant.
const REGIONS: [string, string, string][] = [
  // Eye / ear / nose / mouth — before broad words containing them.
  ['longus colli', 'neck', 'คอ'],
  ['superior oblique', 'eye', 'ตา'],
  ['inferior oblique', 'eye', 'ตา'],
  ['superior rectus', 'eye', 'ตา'],
  ['inferior rectus', 'eye', 'ตา'],
  ['medial rectus', 'eye', 'ตา'],
  ['lateral rectus', 'eye', 'ตา'],
  ['levator palpebrae', 'eye', 'ตา'],
  ['orbicularis oculi', 'face', 'ใบหน้า'],
  ['choroid plexus', 'brain', 'สมอง'],
  ['coronary sinus', 'heart', 'หัวใจ'],
  ['carotid sinus', 'neck', 'คอ'],
  ['malleolus', 'ankle', 'ข้อเท้า'],
  ['masseter', 'face', 'ใบหน้า'],
  ['temporalis', 'face', 'ใบหน้า'],
  ['buccinator', 'face', 'ใบหน้า'],
  ['orbicularis', 'face', 'ใบหน้า'],
  ['zygomaticus', 'face', 'ใบหน้า'],
  ['frontalis', 'face', 'ใบหน้า'],
  ['occipitofrontalis', 'face', 'ใบหน้า'],
  ['procerus', 'face', 'ใบหน้า'],
  ['nasalis', 'face', 'ใบหน้า'],
  ['depressor labii', 'face', 'ใบหน้า'],
  ['depressor anguli', 'face', 'ใบหน้า'],
  ['mentalis', 'face', 'ใบหน้า'],
  ['risorius', 'face', 'ใบหน้า'],
  ['forehead', 'face', 'ใบหน้า'],
  ['chin', 'face', 'ใบหน้า'],
  ['omentum', 'abdomen', 'ช่องท้อง'],
  ['mentum', 'face', 'ใบหน้า'],
  ['facial', 'face', 'ใบหน้า'],
  ['optic', 'eye', 'ตา'],
  ['retinaculum', 'wrist', 'ข้อมือ'],
  ['retina', 'eye', 'ตา'],
  ['cornea', 'eye', 'ตา'],
  ['lens', 'eye', 'ตา'],
  ['iris', 'eye', 'ตา'],
  ['pupil', 'eye', 'ตา'],
  ['sclera', 'eye', 'ตา'],
  ['uvea', 'eye', 'ตา'],
  ['vitreous', 'eye', 'ตา'],
  ['ciliary', 'eye', 'ตา'],
  ['palpebra', 'eye', 'ตา'],
  ['lacrimal', 'eye', 'ตา'],
  ['conjunctiva', 'eye', 'ตา'],
  ['macula', 'eye', 'ตา'],
  ['optic papilla', 'eye', 'ตา'],
  ['renal papilla', 'kidney', 'ไต'],
  ['dental papilla', 'mouth', 'ช่องปาก'],
  ['heart', 'heart', 'หัวใจ'],
  ['cardiac', 'heart', 'หัวใจ'],
  ['coronary', 'heart', 'หัวใจ'],
  ['myocardial', 'heart', 'หัวใจ'],
  ['papillary', 'heart', 'หัวใจ'],
  ['atrium', 'heart', 'หัวใจ'],
  ['mitral', 'heart', 'หัวใจ'],
  ['tricuspid', 'heart', 'หัวใจ'],
  ['aorta', 'chest and abdomen', 'ช่องอกและช่องท้อง'],
  ['aortic valve', 'heart', 'หัวใจ'],
  ['pulmonary valve', 'heart', 'หัวใจ'],
  ['pulmonary', 'lung', 'ปอด'],
  ['bronch', 'lung', 'ปอด'],
  ['alveolar', 'lung', 'ปอด'],
  ['hepatic', 'liver', 'ตับ'],
  ['liver', 'liver', 'ตับ'],
  ['adrenal', 'endocrine glands', 'ต่อมไร้ท่อ'],
  ['renal', 'kidney', 'ไต'],
  ['kidney', 'kidney', 'ไต'],
  ['nephric', 'kidney', 'ไต'],
  ['digastric', 'neck', 'คอ'],
  ['epigastric', 'abdomen', 'ช่องท้อง'],
  ['gastric', 'stomach', 'กระเพาะอาหาร'],
  ['stomach', 'stomach', 'กระเพาะอาหาร'],
  ['splenic', 'spleen', 'ม้าม'],
  ['spleen', 'spleen', 'ม้าม'],
  ['pancreatic', 'pancreas', 'ตับอ่อน'],
  ['pancreas', 'pancreas', 'ตับอ่อน'],
  ['olfactory', 'nose', 'จมูก'],
  ['turbinate', 'nose', 'จมูก'],
  ['choana', 'nose', 'จมูก'],
  ['nasal cavity', 'nose', 'จมูก'],
  ['nasal', 'nose', 'จมูก'],
  ['nostril', 'nose', 'จมูก'],
  ['concha', 'nose', 'จมูก'],
  ['sinus', 'nose', 'จมูก'],
  ['gingiva', 'mouth', 'ช่องปาก'],
  ['dental', 'mouth', 'ช่องปาก'],
  ['tooth', 'mouth', 'ช่องปาก'],
  ['teeth', 'mouth', 'ช่องปาก'],
  ['tongue', 'mouth', 'ช่องปาก'],
  ['lingual', 'mouth', 'ช่องปาก'],
  ['palate', 'mouth', 'ช่องปาก'],
  ['salivary', 'mouth', 'ช่องปาก'],
  ['pharynx', 'throat', 'คอหอย'],
  ['larynx', 'throat', 'กล่องเสียง'],
  ['laryngeal', 'throat', 'กล่องเสียง'],
  ['thyroid cartilage', 'throat', 'กล่องเสียง'],
  ['cricoid', 'throat', 'กล่องเสียง'],
  ['epiglottis', 'throat', 'กล่องเสียง'],
  ['tonsil', 'throat', 'คอหอย'],
  ['oral cavity', 'mouth', 'ช่องปาก'],
  ['oblique arytenoid', 'throat', 'กล่องเสียง'],
  ['transverse arytenoid', 'throat', 'กล่องเสียง'],
  ['arytenoid', 'throat', 'กล่องเสียง'],
  ['thyro-arytenoid', 'throat', 'กล่องเสียง'],
  ['cricothyroid', 'throat', 'กล่องเสียง'],
  ['vocalis', 'throat', 'กล่องเสียง'],
  ['glottis', 'throat', 'กล่องเสียง'],
  ['trachea', 'throat', 'หลอดลม'],
  ['duodenum', 'small intestine', 'ลำไส้เล็ก'],
  ['jejunum', 'small intestine', 'ลำไส้เล็ก'],
  ['ileum', 'small intestine', 'ลำไส้เล็ก'],
  ['ileocecal', 'large intestine', 'ลำไส้ใหญ่'],
  ['colon', 'large intestine', 'ลำไส้ใหญ่'],
  ['cecum', 'large intestine', 'ลำไส้ใหญ่'],
  ['appendix', 'large intestine', 'ลำไส้ใหญ่'],
  ['esophagus', 'chest', 'ทรวงอก'],
  ['obliquus capitis', 'neck', 'คอ'],
  ['colliculus', 'brain', 'สมอง'],
  ['longus capitis', 'neck', 'คอ'],
  ['rectus capitis', 'neck', 'คอ'],
  ['colli', 'neck', 'คอ'],
  ['sternocleidomastoid', 'neck', 'คอ'],
  ['scalene', 'neck', 'คอ'],
  ['splenius', 'neck', 'คอ'],
  ['semispinalis cervicis', 'neck', 'คอ'],
  ['semispinalis capitis', 'neck', 'คอ'],
  ['platysma', 'neck', 'คอ'],
  ['mylohyoid', 'neck', 'คอ'],
  ['omohyoid', 'neck', 'คอ'],
  ['sternohyoid', 'neck', 'คอ'],
  ['sternothyroid', 'neck', 'คอ'],
  ['stylohyoid', 'neck', 'คอ'],
  ['geniohyoid', 'neck', 'คอ'],
  ['thyrohyoid', 'neck', 'คอ'],
  ['hyoid', 'neck', 'คอ'],
  ['cervical vertebra', 'neck', 'คอ'],
  ['cervical rotator', 'neck', 'คอ'],
  ['carotid', 'neck', 'คอ'],
  ['jugular', 'neck', 'คอ'],
  ['thyroid', 'neck', 'คอ'],
  ['parathyroid', 'neck', 'คอ'],
  ['trapezius', 'neck and shoulder', 'คอและไหล่'],
  ['cranial', 'head', 'ศีรษะ'],
  ['cerebral', 'brain', 'สมอง'],
  ['cerebellar', 'brain', 'สมอง'],
  ['cerebellum', 'brain', 'สมอง'],
  ['brainstem', 'brain', 'สมอง'],
  ['oblongata', 'brain', 'สมอง'],
  ['pons', 'brain', 'สมอง'],
  ['thalamus', 'brain', 'สมอง'],
  ['hypothalamus', 'brain', 'สมอง'],
  ['hippocampus', 'brain', 'สมอง'],
  ['amygdala', 'brain', 'สมอง'],
  ['corpus callosum', 'brain', 'สมอง'],
  ['commissure', 'brain', 'สมอง'],
  ['longitudinal fissure', 'brain', 'สมอง'],
  ['sulcus', 'brain', 'สมอง'],
  ['gyrus', 'brain', 'สมอง'],
  ['frontal lobe', 'brain', 'สมอง'],
  ['parietal lobe', 'brain', 'สมอง'],
  ['temporal lobe', 'brain', 'สมอง'],
  ['occipital lobe', 'brain', 'สมอง'],
  ['spinal cord', 'spine', 'กระดูกสันหลัง'],
  ['cauda equina', 'spine', 'กระดูกสันหลัง'],
  ['dura', 'central nervous system', 'ระบบประสาทกลาง'],
  ['arachnoid', 'central nervous system', 'ระบบประสาทกลาง'],
  ['frontal', 'head', 'ศีรษะ'],
  ['parietal', 'head', 'ศีรษะ'],
  ['occipital', 'head', 'ศีรษะ'],
  ['temporal', 'head', 'ศีรษะ'],
  ['mandible', 'head', 'ศีรษะ'],
  ['mandibular', 'head', 'ศีรษะ'],
  ['maxilla', 'head', 'ศีรษะ'],
  ['maxillary', 'head', 'ศีรษะ'],
  ['nasal spine', 'nose', 'จมูก'],
  ['mental spine', 'head', 'ศีรษะ'],
  ['zygomatic', 'head', 'ศีรษะ'],
  ['sphenoid', 'head', 'ศีรษะ'],
  ['ethmoid', 'head', 'ศีรษะ'],
  ['vomer', 'head', 'ศีรษะ'],
  ['skull', 'head', 'ศีรษะ'],
  ['cranium', 'head', 'ศีรษะ'],
  ['suture', 'head', 'ศีรษะ'],
  ['fontanelle', 'head', 'ศีรษะ'],
  ['mastoid', 'ear', 'หู'],
  ['auditory', 'ear', 'หู'],
  ['cochlea', 'ear', 'หู'],
  ['semicircular', 'ear', 'หู'],
  ['ossicle', 'ear', 'หู'],
  ['tympanic', 'ear', 'หู'],
  ['auricular', 'ear', 'หู'],
  ['otic', 'ear', 'หู'],
  ['deltoideus', 'shoulder', 'ไหล่'],
  ['deltoid', 'shoulder', 'ไหล่'],
  ['acromion', 'shoulder', 'ไหล่'],
  ['acromioclavicular', 'shoulder', 'ไหล่'],
  ['glenohumeral', 'shoulder', 'ไหล่'],
  ['glenoid', 'shoulder', 'ไหล่'],
  ['supraspinatus', 'shoulder', 'ไหล่'],
  ['infraspinatus', 'shoulder', 'ไหล่'],
  ['subscapularis', 'shoulder', 'ไหล่'],
  ['axilla', 'shoulder', 'ไหล่'],
  ['axillary', 'shoulder', 'ไหล่'],
  ['subclavius', 'shoulder', 'ไหล่'],
  ['subclavian', 'shoulder', 'ไหล่'],
  ['clavicle', 'shoulder', 'ไหล่'],
  ['scapula', 'shoulder', 'ไหล่'],
  ['spine of scapula', 'shoulder', 'ไหล่'],
  ['serratus anterior', 'shoulder', 'ไหล่'],
  ['coracoid', 'shoulder', 'ไหล่'],
  ['biceps brachii', 'upper arm', 'ต้นแขน'],
  ['triceps brachii', 'upper arm', 'ต้นแขน'],
  ['brachialis', 'upper arm', 'ต้นแขน'],
  ['coracobrachialis', 'upper arm', 'ต้นแขน'],
  ['femoral epicondyle', 'knee', 'เข่า'],
  ['humeral epicondyle', 'elbow', 'ข้อศอก'],
  ['antebrachial', 'forearm', 'ปลายแขน'],
  ['brachial', 'upper arm', 'ต้นแขน'],
  ['humerus', 'upper arm', 'ต้นแขน'],
  ['humeral', 'upper arm', 'ต้นแขน'],
  ['olecranon', 'elbow', 'ข้อศอก'],
  ['cubital', 'elbow', 'ข้อศอก'],
  ['elbow', 'elbow', 'ข้อศอก'],
  ['anconeus', 'elbow', 'ข้อศอก'],
  ['pronator', 'forearm', 'ปลายแขน'],
  ['supinator', 'forearm', 'ปลายแขน'],
  ['brachioradialis', 'forearm', 'ปลายแขน'],
  ['radialis', 'forearm', 'ปลายแขน'],
  ['ulnaris', 'forearm', 'ปลายแขน'],
  ['radius', 'forearm', 'ปลายแขน'],
  ['ulna', 'forearm', 'ปลายแขน'],
  ['radial', 'forearm', 'ปลายแขน'],
  ['ulnar', 'forearm', 'ปลายแขน'],
  ['carpal tunnel', 'wrist', 'ข้อมือ'],
  ['carpus', 'wrist', 'ข้อมือ'],
  ['metacarpal', 'hand', 'มือ'],
  ['carpal', 'wrist', 'ข้อมือ'],
  ['wrist', 'wrist', 'ข้อมือ'],
  ['scaphoid', 'wrist', 'ข้อมือ'],
  ['lunate', 'wrist', 'ข้อมือ'],
  ['triquetrum', 'wrist', 'ข้อมือ'],
  ['pisiform', 'wrist', 'ข้อมือ'],
  ['trapezium', 'wrist', 'ข้อมือ'],
  ['trapezoid', 'wrist', 'ข้อมือ'],
  ['capitate', 'wrist', 'ข้อมือ'],
  ['hamate', 'wrist', 'ข้อมือ'],
  ['pollicis', 'hand', 'มือ'],
  ['opponens pollicis', 'hand', 'มือ'],
  ['thenar', 'hand', 'มือ'],
  ['hypothenar', 'hand', 'มือ'],
  ['palmar', 'hand', 'มือ'],
  ['of hand', 'hand', 'มือ'],
  ['finger', 'hand', 'มือ'],
  ['thumb', 'hand', 'มือ'],
  ['extensor digitorum longus', 'lower leg', 'ขาท่อนล่าง'],
  ['extensor digitorum brevis', 'foot', 'เท้า'],
  ['extensor digitorum', 'hand', 'มือ'],
  ['flexor digitorum superficialis', 'forearm', 'ปลายแขน'],
  ['flexor digitorum profundus', 'forearm', 'ปลายแขน'],
  ['pectoralis', 'chest', 'ทรวงอก'],
  ['mammary', 'chest', 'ทรวงอก'],
  ['breast', 'chest', 'ทรวงอก'],
  ['nipple', 'chest', 'ทรวงอก'],
  ['intercostal', 'chest', 'ทรวงอก'],
  ['iliocostalis', 'back', 'หลัง'],
  ['costal cartilage', 'chest', 'ทรวงอก'],
  ['costal', 'chest', 'ทรวงอก'],
  ['sternum', 'chest', 'ทรวงอก'],
  ['manubrium', 'chest', 'ทรวงอก'],
  ['xiphoid', 'chest', 'ทรวงอก'],
  ['thorax', 'chest', 'ทรวงอก'],
  ['thoracic cavity', 'chest', 'ทรวงอก'],
  ['mediastinum', 'chest', 'ทรวงอก'],
  ['pleura', 'chest', 'ทรวงอก'],
  ['pericardium', 'chest', 'ทรวงอก'],
  ['aortic arch', 'chest', 'ทรวงอก'],
  ['diaphragm', 'chest and abdomen', 'ช่องอกและช่องท้อง'],
  ['rectus abdominis', 'abdomen', 'ช่องท้อง'],
  ['linea alba', 'abdomen', 'ช่องท้อง'],
  ['rectus sheath', 'abdomen', 'ช่องท้อง'],
  ['external oblique', 'abdomen', 'ช่องท้อง'],
  ['obliquus externus', 'abdomen', 'ช่องท้อง'],
  ['obliquus internus', 'abdomen', 'ช่องท้อง'],
  ['transversus abdominis', 'abdomen', 'ช่องท้อง'],
  ['abdominal', 'abdomen', 'ช่องท้อง'],
  ['abdomen', 'abdomen', 'ช่องท้อง'],
  ['umbilicus', 'abdomen', 'ช่องท้อง'],
  ['peritoneum', 'abdomen', 'ช่องท้อง'],
  ['mesentery', 'abdomen', 'ช่องท้อง'],
  ['celiac', 'abdomen', 'ช่องท้อง'],
  ['portal vein', 'abdomen', 'ช่องท้อง'],
  ['groin', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['inguinal', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['iliac spine', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['iliac crest', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['ilium', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['ischium', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['ischial', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['pubis', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['pubic', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['acetabulum', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['acetabular', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['obturator foramen', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['obturator', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['piriformis', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['gemellus', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['coccygeus', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['pubococcygeus', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['gluteal', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['gluteus', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['pelvis', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['pelvic', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['sacrum', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['sacral', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['coccyx', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['perineum', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['psoas', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['iliacus', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['sciatic', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['pudendal', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['testis', 'external genitalia', 'อวัยวะเพศภายนอก'],
  ['epididymis', 'external genitalia', 'อวัยวะเพศภายนอก'],
  ['prostate', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['penis', 'external genitalia', 'อวัยวะเพศภายนอก'],
  ['seminal vesicle', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['gallbladder', 'abdomen', 'ช่องท้อง'],
  ['bladder', 'urinary tract', 'ทางเดินปัสสาวะ'],
  ['ureter', 'urinary tract', 'ทางเดินปัสสาวะ'],
  ['urethra', 'urinary tract', 'ทางเดินปัสสาวะ'],
  ['vesical', 'urinary tract', 'ทางเดินปัสสาวะ'],
  ['rectum', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['anus', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['anal canal', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['rectus femoris', 'thigh', 'ต้นขา'],
  ['vastus', 'thigh', 'ต้นขา'],
  ['sartorius', 'thigh', 'ต้นขา'],
  ['gracilis', 'thigh', 'ต้นขา'],
  ['adductor longus', 'thigh', 'ต้นขา'],
  ['adductor brevis', 'thigh', 'ต้นขา'],
  ['adductor magnus', 'thigh', 'ต้นขา'],
  ['adductor minimus', 'thigh', 'ต้นขา'],
  ['pectineus', 'thigh', 'ต้นขา'],
  ['biceps femoris', 'thigh', 'ต้นขา'],
  ['semitendinosus', 'thigh', 'ต้นขา'],
  ['semimembranosus', 'thigh', 'ต้นขา'],
  ['quadriceps', 'thigh', 'ต้นขา'],
  ['hamstring', 'thigh', 'ต้นขา'],
  ['femoral', 'thigh', 'ต้นขา'],
  ['femur', 'thigh', 'ต้นขา'],
  ['upper limb', 'arm', 'แขน'],
  ['lower limb', 'leg', 'ขา'],
  ['patella', 'knee', 'เข่า'],
  ['patellar', 'knee', 'เข่า'],
  ['meniscus', 'knee', 'เข่า'],
  ['cruciate', 'knee', 'เข่า'],
  ['fibular collateral', 'knee', 'เข่า'],
  ['tibial collateral', 'knee', 'เข่า'],
  ['popliteus', 'knee', 'เข่า'],
  ['knee', 'knee', 'เข่า'],
  ['genu', 'knee', 'เข่า'],
  ['tibialis', 'lower leg', 'ขาท่อนล่าง'],
  ['tibial tuberosity', 'knee', 'เข่า'],
  ['tibia', 'lower leg', 'ขาท่อนล่าง'],
  ['fibula', 'lower leg', 'ขาท่อนล่าง'],
  ['fibular', 'lower leg', 'ขาท่อนล่าง'],
  ['peroneus', 'lower leg', 'ขาท่อนล่าง'],
  ['peroneal', 'lower leg', 'ขาท่อนล่าง'],
  ['gastrocnemius', 'lower leg', 'ขาท่อนล่าง'],
  ['soleus', 'lower leg', 'ขาท่อนล่าง'],
  ['sural', 'lower leg', 'ขาท่อนล่าง'],
  ['crural', 'lower leg', 'ขาท่อนล่าง'],
  ['triceps surae', 'lower leg', 'ขาท่อนล่าง'],
  ['plantaris', 'lower leg', 'ขาท่อนล่าง'],
  ['flexor digitorum longus', 'lower leg', 'ขาท่อนล่าง'],
  ['flexor hallucis longus', 'lower leg', 'ขาท่อนล่าง'],
  ['ankle', 'ankle', 'ข้อเท้า'],
  ['talus', 'foot', 'เท้า'],
  ['calcaneus', 'foot', 'เท้า'],
  ['navicular', 'foot', 'เท้า'],
  ['cuboid', 'foot', 'เท้า'],
  ['cuneiform', 'foot', 'เท้า'],
  ['metatarsal', 'foot', 'เท้า'],
  ['hallux', 'foot', 'เท้า'],
  ['flexor digitorum brevis', 'foot', 'เท้า'],
  ['flexor hallucis brevis', 'foot', 'เท้า'],
  ['abductor hallucis', 'foot', 'เท้า'],
  ['adductor hallucis', 'foot', 'เท้า'],
  ['opponens digiti minimi of foot', 'foot', 'เท้า'],
  ['of foot', 'foot', 'เท้า'],
  ['plantar', 'foot', 'เท้า'],
  ['lumbar vertebra', 'lower back', 'หลังส่วนล่าง'],
  ['lumbar rotator', 'lower back', 'หลังส่วนล่าง'],
  ['quadratus lumborum', 'lower back', 'หลังส่วนล่าง'],
  ['thoracic vertebra', 'back', 'หลัง'],
  ['spinalis', 'back', 'หลัง'],
  ['semispinalis thoracis', 'back', 'หลัง'],
  ['multifidus', 'back', 'หลัง'],
  ['rotator', 'back', 'หลัง'],
  ['interspinalis', 'back', 'หลัง'],
  ['longissimus', 'back', 'หลัง'],
  ['erector spinae', 'back', 'หลัง'],
  ['latissimus', 'back', 'หลัง'],
  ['rhomboid', 'back', 'หลัง'],
  ['serratus posterior', 'back', 'หลัง'],
  ['levatores', 'back', 'หลัง'],
  ['vertebral artery', 'neck', 'คอ'],
  ['vertebra', 'spine', 'กระดูกสันหลัง'],
  ['intervertebral disc', 'spine', 'กระดูกสันหลัง'],
  ['skin', 'skin', 'ผิวหนัง'],
  ['cutaneous', 'skin', 'ผิวหนัง'],
  ['nail', 'digits', 'นิ้วมือและนิ้วเท้า'],
  ['phalanx', 'digits', 'นิ้วมือและนิ้วเท้า'],
  ['artery', 'blood vessels', 'หลอดเลือด'],
  ['arterial', 'blood vessels', 'หลอดเลือด'],
  ['vein', 'blood vessels', 'หลอดเลือด'],
  ['venous', 'blood vessels', 'หลอดเลือด'],
  ['capillary', 'blood vessels', 'หลอดเลือด'],
  ['nerve', 'nerves', 'เส้นประสาท'],
  ['plexus', 'nerves', 'เส้นประสาท'],
  ['ganglion', 'nerves', 'เส้นประสาท'],
  ['lymph node', 'lymph nodes', 'ต่อมน้ำเหลือง'],
  ['lymph', 'lymph nodes', 'ต่อมน้ำเหลือง'],
  ['pituitary', 'endocrine glands', 'ต่อมไร้ท่อ'],
  ['gland', 'glands', 'ต่อม'],
  ['pineal', 'endocrine glands', 'ต่อมไร้ท่อ'],
  ['thymus', 'endocrine glands', 'ต่อมไร้ท่อ'],
  ['hip', 'hip and pelvis', 'สะโพกและเชิงกราน'],
  ['shoulder', 'shoulder', 'ไหล่'],
  ['thoracic duct', 'chest', 'ทรวงอก'],
  ['cisterna chyli', 'abdomen', 'ช่องท้อง'],
];

export function stripSides(name: string): string {
  return name.replace(/(^|\s)(left|right)(?=\s|$)/gi, ' ').replace(/\s+/g, ' ').trim();
}

function cap(s: string): string {
  return s.length ? s[0].toUpperCase() + s.slice(1) : s;
}

function regionLookup(strippedLower: string): { en: string; th: string } | null {
  for (const [k, en, th] of REGIONS) {
    if (strippedLower.includes(k)) return { en, th };
  }
  return null;
}

export interface ConceptDescription {
  en: string;
  th: string;
}

export type EmgInfo = Pick<SeniamEntry, 'origin' | 'insertion' | 'function'>;

export function describeConcept(concept: Concept, system: SystemId, entry?: EmgInfo | null): ConceptDescription {
  const name = concept.name;
  const lower = name.toLowerCase();
  const stripped = stripSides(lower);
  const region = regionLookup(stripped);
  const sys = SYSTEMS.find((s) => s.id === system);
  // Avoid "(x)" redundancy when the region repeats the name.
  let regionEn = region?.en ?? '';
  let regionTh = region?.th ?? '';
  if (regionEn && (stripped.includes(regionEn) || regionEn.includes(stripped))) {
    regionEn = '';
    regionTh = '';
  }
  const headEn = regionEn ? `${cap(name)} (${regionEn}).` : `${cap(name)}.`;
  const headTh = regionTh ? `${name} (${regionTh}).` : `${name}.`;
  if (entry?.origin && entry?.insertion) {
    const f = entry.function;
    return {
      en: `${headEn} Origin: ${entry.origin.en}. Insertion: ${entry.insertion.en}.${f ? ` Function: ${f.en}.` : ''}`,
      th: `${headTh} จุดเกาะต้น: ${entry.origin.th}. จุดเกาะปลาย: ${entry.insertion.th}.${f ? ` หน้าที่: ${f.th}.` : ''}`,
    };
  }
  const fn = EXPLANATIONS[stripped] ? { en: EXPLANATIONS[stripped], th: EXPLANATIONS_TH[stripped] ?? EXPLANATIONS[stripped] } : null;
  const bodyEn = fn?.en ?? sys?.description ?? '';
  const bodyTh = fn?.th ?? sys?.descriptionTh ?? '';
  return { en: `${headEn} ${bodyEn}`.trim(), th: `${headTh} ${bodyTh}`.trim() };
}